// Code generated by "stringer -type=EventType"; DO NOT EDIT

package kv

import "fmt"

const eventTypeName = "NoneCreateDeleteUpdate"

var eventTypeIndex = [...]uint8{0, 4, 10, 16, 22}

func (i EventType) String() string {
	if i < 0 || i >= EventType(len(eventTypeIndex)-1) {
		return fmt.Sprintf("EventType(%d)", i)
	}
	return eventTypeName[eventTypeIndex[i]:eventTypeIndex[i+1]]
}
