// generated by stringer -type=dataType; DO NOT EDIT

package nv

import "fmt"

const _dataType_name = "UNKNOWNBOOLEANBYTEINT16UINT16INT32UINT32INT64UINT64STRINGBYTE_ARRAYINT16_ARRAYUINT16_ARRAYINT32_ARRAYUINT32_ARRAYINT64_ARRAYUINT64_ARRAYSTRING_ARRAYHRTIMENVLISTNVLIST_ARRAYBOOLEAN_VALUEINT8UINT8BOOLEAN_ARRAYINT8_ARRAYUINT8_ARRAYDOUBLE"

var _dataType_index = [...]uint8{0, 7, 14, 18, 23, 29, 34, 40, 45, 51, 57, 67, 78, 90, 101, 113, 124, 136, 148, 154, 160, 172, 185, 189, 194, 207, 217, 228, 234}

func (i dataType) String() string {
	if i >= dataType(len(_dataType_index)-1) {
		return fmt.Sprintf("dataType(%d)", i)
	}
	return _dataType_name[_dataType_index[i]:_dataType_index[i+1]]
}
