// generated by stringer -type=flag; DO NOT EDIT

package nv

import "fmt"

const _flag_name = "UNIQUE_NAMEUNIQUE_NAME_TYPE"

var _flag_index = [...]uint8{0, 11, 27}

func (i flag) String() string {
	i -= 1
	if i >= flag(len(_flag_index)-1) {
		return fmt.Sprintf("flag(%d)", i+1)
	}
	return _flag_name[_flag_index[i]:_flag_index[i+1]]
}
