#!/bin/bash -x

zfs destroy -R data/datasets/testing
zfs destroy -R data/running-clones/testing

set -o errexit
zfs create data/datasets/testing
zfs create data/running-clones/testing

zfs create data/datasets/testing/source_no_snaps1
zfs create data/datasets/testing/source_no_snaps2
zfs create data/datasets/testing/source_snapped
zfs snapshot data/datasets/testing/source_snapped@initial

create_the_clones() {
    rollback_clone data/datasets/testing/source_snapped@initial data/running-clones/testing/test1
    rollback_clone data/datasets/testing/source_snapped data/running-clones/testing/test2
    rollback_clone data/datasets/testing/source_snapped@something_else data/running-clones/testing/test3
    rollback_clone data/datasets/testing/source_snapped data/running-clones/testing/test4
    rollback_clone data/datasets/testing/source_no_snaps1 data/running-clones/testing/test5
    rollback_clone data/datasets/testing/source_no_snaps1 data/running-clones/testing/test6
    rollback_clone data/datasets/testing/source_no_snaps1@new_snap data/running-clones/testing/test7
    rollback_clone data/datasets/testing/source_no_snaps2@something data/running-clones/testing/test8
    rollback_clone data/datasets/testing/source_no_snaps2 data/running-clones/testing/test9
}

create_the_clones

diff -u - <(zfs get -H -r origin -o name,value -t filesystem data/running-clones/testing) <<"EOF"
data/running-clones/testing     -
data/running-clones/testing/test1       data/datasets/testing/source_snapped@initial
data/running-clones/testing/test2       data/datasets/testing/source_snapped@initial
data/running-clones/testing/test3       data/datasets/testing/source_snapped@something_else
data/running-clones/testing/test4       data/datasets/testing/source_snapped@something_else
data/running-clones/testing/test5       data/datasets/testing/source_no_snaps1@test5
data/running-clones/testing/test6       data/datasets/testing/source_no_snaps1@test5
data/running-clones/testing/test7       data/datasets/testing/source_no_snaps1@new_snap
data/running-clones/testing/test8       data/datasets/testing/source_no_snaps2@something
data/running-clones/testing/test9       data/datasets/testing/source_no_snaps2@something
EOF

create_the_clones

diff -u - <(zfs get -H -r origin -o name,value -t filesystem data/running-clones/testing) <<"EOF"
data/running-clones/testing     -
data/running-clones/testing/test1       data/datasets/testing/source_snapped@initial
data/running-clones/testing/test2       data/datasets/testing/source_snapped@something_else
data/running-clones/testing/test3       data/datasets/testing/source_snapped@something_else
data/running-clones/testing/test4       data/datasets/testing/source_snapped@something_else
data/running-clones/testing/test5       data/datasets/testing/source_no_snaps1@new_snap
data/running-clones/testing/test6       data/datasets/testing/source_no_snaps1@new_snap
data/running-clones/testing/test7       data/datasets/testing/source_no_snaps1@new_snap
data/running-clones/testing/test8       data/datasets/testing/source_no_snaps2@something
data/running-clones/testing/test9       data/datasets/testing/source_no_snaps2@something
EOF

zfs snapshot -r data/datasets/testing@latest
zfs snapshot -r data/running-clones/testing@evil-snapshot

create_the_clones

diff -u - <(zfs get -H -r origin -o name,value -t filesystem data/running-clones/testing) <<"EOF"
data/running-clones/testing     -
data/running-clones/testing/test1       data/datasets/testing/source_snapped@initial
data/running-clones/testing/test2       data/datasets/testing/source_snapped@latest
data/running-clones/testing/test3       data/datasets/testing/source_snapped@something_else
data/running-clones/testing/test4       data/datasets/testing/source_snapped@latest
data/running-clones/testing/test5       data/datasets/testing/source_no_snaps1@latest
data/running-clones/testing/test6       data/datasets/testing/source_no_snaps1@latest
data/running-clones/testing/test7       data/datasets/testing/source_no_snaps1@new_snap
data/running-clones/testing/test8       data/datasets/testing/source_no_snaps2@something
data/running-clones/testing/test9       data/datasets/testing/source_no_snaps2@latest
EOF

zfs destroy -R data/datasets/testing
zfs destroy -R data/running-clones/testing
