// Code generated by "stringer -type=codec"; DO NOT EDIT

package nv

import "fmt"

const codecName = "nativeCodecxdrCodec"

var codecIndex = [...]uint8{0, 11, 19}

func (i codec) String() string {
	if i >= codec(len(codecIndex)-1) {
		return fmt.Sprintf("codec(%d)", i)
	}
	return codecName[codecIndex[i]:codecIndex[i+1]]
}
