// Code generated by "stringer -type=dataType"; DO NOT EDIT

package nv

import "fmt"

const dataTypeName = "_unknown_boolean_byte_int16_uint16_int32_uint32_int64_uint64_string_byteArray_int16Array_uint16Array_int32Array_uint32Array_int64Array_uint64Array_stringArray_hrtime_nvlist_nvlistArray_booleanValue_int8_uint8_booleanArray_int8Array_uint8Array_double"

var dataTypeIndex = [...]uint8{0, 8, 16, 21, 27, 34, 40, 47, 53, 60, 67, 77, 88, 100, 111, 123, 134, 146, 158, 165, 172, 184, 197, 202, 208, 221, 231, 242, 249}

func (i dataType) String() string {
	if i >= dataType(len(dataTypeIndex)-1) {
		return fmt.Sprintf("dataType(%d)", i)
	}
	return dataTypeName[dataTypeIndex[i]:dataTypeIndex[i+1]]
}
