// Code generated by "stringer -type=endianness"; DO NOT EDIT

package nv

import "fmt"

const endiannessName = "bigEndianlittleEndian"

var endiannessIndex = [...]uint8{0, 9, 21}

func (i endianness) String() string {
	if i >= endianness(len(endiannessIndex)-1) {
		return fmt.Sprintf("endianness(%d)", i)
	}
	return endiannessName[endiannessIndex[i]:endiannessIndex[i+1]]
}
