// Code generated by "stringer -type=flag"; DO NOT EDIT

package nv

import "fmt"

const flagName = "ignoreMeuniqueNameuniqueNameType"

var flagIndex = [...]uint8{0, 8, 18, 32}

func (i flag) String() string {
	if i >= flag(len(flagIndex)-1) {
		return fmt.Sprintf("flag(%d)", i)
	}
	return flagName[flagIndex[i]:flagIndex[i+1]]
}
