// Code generated by "stringer -type=flag"; DO NOT EDIT

package nv

import "fmt"

const flagName = "uniqueNameuniqueNameType"

var flagIndex = [...]uint8{0, 10, 24}

func (i flag) String() string {
	i -= 1
	if i >= flag(len(flagIndex)-1) {
		return fmt.Sprintf("flag(%d)", i+1)
	}
	return flagName[flagIndex[i]:flagIndex[i+1]]
}
