language: go
dist: trusty

go:
  - 1.5
  - 1.6
  - tip

before_install:
  - go get github.com/alecthomas/gometalinter
  - gometalinter --install --update

install:
  - go get -t -v ./...

script:
  - gometalinter --disable-all --enable=goimports --enable=errcheck --enable=vet --enable=gofmt --enable=golint --enable=vetshadow --deadline=30s ./...
  - go test -v ./...

after_success:
  - gometalinter --disable=errcheck --disable=vet --disable=gofmt --disable=golint --disable=vetshadow --deadline=30s ./...

notifications:
  email: false
  slack:
    secure: "RvfAmeiERh2Ua2mTnXsIJkV+11g5NUfKAvHc1+dz4T9Jr4oa4/+sV/7K/nQXDq+4bwzWPIDOqBBApi/dl6HM4BqG4TL3d5LV2e6vE2ZvnSlnrNf6ALcLk3VZvY/1EZQ0easmqfkw7iWQ5UefEDAIpoqZ7UfefOgF2RJOjrmbDP/jT4paXNUAVZk1TMyHVVZitXdiIIj2jgpBtxjjLmP6lCwJeA5GVQRxpeBTGP35J39mwPBVTdj+KkTovBVgujQhB/Yl5GphWHMcQLCLSJ6adtkaXLWF7liSL7li7prqSB6POY+WVHjwaMgEO6kVb7qq8u8mFmVJfVTpZdcEh15sxQ1Kcwfx5rLstk9D70XgitgPtgYUkzhukpuXZmmp3/Yo9XCkhU5TZJWmKJqeho2WZ2Hbip/QN6f8PfURgMcSXO5qGWDqB7vtelCz6xOt/TzL5wEx1vrl4w3X9/0Ls8hhReE6+w3bLQRN3+gawrmMDIA3swY1jb7OUeQkArQZu5myIAN7VJxNYuJdnytt0wzMhMtzRdENCRa0qAmVxzacqZMAdnmCV0PD2XZIVH3bIfmdaCJidrNWuZAMDlu2W2y4JhB2cuij5kny3t2DqdF5udFl4VBAxVKVV8+aNc7U1mphEAZlRhwkQXK6wJpsERrpPI8O9Y/BaQbvaMqMAVx4AbA="
