[
  ./nixpkgs-overlay.nix
  ./services/cerana/bootserver.nix
  ./services/cerana/bootstrap.nix
  ./services/cerana/bundle-heartbeat.nix
  ./services/cerana/cerana-target.nix
  ./services/cerana/clusterconf-provider.nix
  ./services/cerana/consul.nix
  ./services/cerana/coordinator.nix
  ./services/cerana/dataset-heartbeat.nix
  ./services/cerana/datatrade-provider.nix
  ./services/cerana/dhcp-provider.nix
  ./services/cerana/health-provider.nix
  ./services/cerana/kv-provider.nix
  ./services/cerana/l2-coordinator.nix
  ./services/cerana/l2-services.nix
  ./services/cerana/metrics-provider.nix
  ./services/cerana/move-logs.nix
  ./services/cerana/namespace-provider.nix
  ./services/cerana/network.nix
  ./services/cerana/node-heartbeat.nix
  ./services/cerana/platform-import.nix
  ./services/cerana/pool.nix
  ./services/cerana/service-provider.nix
  ./services/cerana/systemd-provider.nix
  ./services/cerana/zfs-provider.nix
]
